theme: jekyll-theme-minimal
title: Daniel Kwan
description: >- # this means to ignore newlines until "baseurl:"
  Tech Passionate 3rd year data science student at Wilfrid Laurier University
Resources:
  LinkedIn: "https://www.linkedin.com/in/dkwan2000"
  email: danielkwan2000@gmail.com
github_username:  ddanielkwan
logo: "/images/me.png"
