theme: jekyll-theme-minimal
title: Daniel Kwan
email: danielkwan2000@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Aspiring Data Scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ddanielkwan
logo: "/images/me.png"
